name: CI Water Quality Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data quality checks
        run: |
          python src/pyspark/quality/validate_silver_with_ge.py